[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
example = "EKHAW46PDD4TiJnke4ofM5FpqsVT3pg6xsoB9X9TBuK4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
