[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
example = "FuACQ49TzPjXDBWjjvu6wi2hwsxxTqAoZVaJEVzTho98"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
