[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
example = "AUffEiJB7q81Zww8ireHXdncMef53kyvqpPiPMo9iD5u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
